# Generated by Django 4.1.5 on 2023-02-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PassImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('img', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bTitle', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('other_title', models.CharField(max_length=100)),
                ('connect', models.CharField(max_length=100)),
                ('spring', models.CharField(max_length=100)),
                ('summer', models.CharField(max_length=100)),
                ('autumn', models.CharField(max_length=100)),
                ('winter', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'новое'), ('pending', 'взято в работу'), ('accepted', 'успешно'), ('rejected', 'не принято')], default='new', max_length=255)),
                ('coord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coord_id', to='fstr.coordinates')),
                ('pass_images', models.ManyToManyField(through='fstr.Images', to='fstr.passimages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.user')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='pass_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.pass'),
        ),
        migrations.AddField(
            model_name='images',
            name='pass_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.passimages'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pass_added', models.ManyToManyField(to='fstr.pass')),
            ],
        ),
    ]
