# Generated by Django 4.1.5 on 2023-02-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'pass_coordinates',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(blank=True, max_length=3)),
                ('summer_level', models.CharField(blank=True, max_length=3)),
                ('autumn_level', models.CharField(blank=True, max_length=3)),
                ('spring_level', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'db_table': 'pass_level',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'pass_user',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'новое'), ('pending', 'взято в работу'), ('accepted', 'успешно'), ('rejected', 'не принято')], default='new', max_length=8)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.coordinates')),
                ('levels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='fstr.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fstr.user')),
            ],
            options={
                'db_table': 'pass_pass',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
                ('data', models.BinaryField()),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fstr.pass')),
            ],
            options={
                'db_table': 'pass_images',
            },
        ),
    ]
