# Generated by Django 4.1.5 on 2023-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
